pull_request_rules:
  - name: automatic merge on approval and CI pass
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=axa-group.radar
      - label!=WIP
    actions:
      merge:
        method: squash
  - name: merge pull requests from dependabot[bot] if CI passes
    conditions:
      - author=dependabot[bot]
      - status-success=axa-group.radar
    actions:
      merge:
        method: squash
  - name: merge pull requests from dependabot-preview[bot] if CI passes
    conditions:
      - author=dependabot-preview[bot]
      - status-success=axa-group.radar
    actions:
      merge:
        method: squash
