export const FORM_SET_FIELDS = 'FORM_SET_FIELDS';
export const FORM_SET_READONLY_FIELDS = 'FORM_SET_READONLY_FIELDS';
export const FORM_UPDATE_FIELDS = 'FORM_UPDATE_FIELDS';
export const FORM_ON_SUBMIT = 'FORM_ON_SUBMIT';
export const FORM_END_SUBMIT = 'FORM_END_SUBMIT';
export const FORM_SET_ERROR = 'FORM_SET_ERROR';
