export const TABLE_SET_ITEMS = 'TABLE_SET_ITEMS';
export const TABLE_SORT_ITEMS = 'TABLE_SORT_ITEMS';
export const TABLE_UPDATE_FILTERS = 'TABLE_UPDATE_FILTERS';
export const TABLE_UPDATE_PAGING = 'TABLE_UPDATE_PAGING';
